### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedora-python#1]
Could this repo be named fedora-python-docs or something like that? Just fedora-python can mean anything.

**Comment by encukou** [comment]
@ncoghlan?

**Comment by encukou** [comment]
It's meant to be something like a README for Python SIG, so I think the name is fine.

**Comment by ncoghlan** [comment]
I think fedora-python-docs would be more confusing, since it *isn't* the docs for using Python on Fedora - those are in the Fedora Developer Guide.

Calling it fedora-python-sig could be genuinely clearer, though.

**Comment by ncoghlan** [comment]
I'm going to close this, mainly because I don't think it's worth the effort to go through and adjust config settings to append `-sig` to the name, and I also think it's better to remain consistent with the https://fedora-python.readthedocs.io/en/latest/ URL for the rendered docs (and I don't want to add `-sig` to that).
